### ISSUE TITLE
Component import problem

### ISSUE THREAD

**Issue by hakancunier** [pmndrs/its-fine#12]
Last day i updated my npm packages and got this error:

./node_modules/its-fine/dist/index.mjs
Can't import the named export 'Component' from non EcmaScript module (only default export is available)

**Comment by CodyJasonBennett** [comment]
Which tool are you using for this? Webpack? It would help to know which and what version.

**Comment by abhi-dasgupta** [comment]
i started getting this too.. simply by deleting node_modules and running npm i

**Comment by CodyJasonBennett** [comment]
Some basic information about your environment would go a long way to solving this. See the above, a repository recreating the issue would be ideal.

**Comment by abhi-dasgupta** [comment]
ok so this is hot i ended up here.
1. developing with create-react-app
2. faced this issue https://github.com/facebook/create-react-app/issues/12212
3. did what is suggested there and in similar issues, one of steps is downgrading react-scripts
4. previous errors go away and now I get this error
has nothing to do with my code, everything was working fine, until today with npm i ...

**Comment by CodyJasonBennett** [comment]
Downgrading react-scripts puts you to v4 which does not understand Node ESM (related: https://github.com/facebook/create-react-app/issues/10356). Could you try with a clean install on v5?

**Comment by abhi-dasgupta** [comment]
sorry my bad, i get a different set of errors with v4 with v5.0.1 I get the below error on start 
./node_modules/its-fine/dist/index.mjs
Can't import the named export 'Component' from non EcmaScript module (only default export is available)

all packages
"@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@mui/icons-material": "^5.10.6",
    "@mui/material": "^5.10.6",
    "@react-three/drei": "^9.32.1",
    "@react-three/fiber": "^8.8.2",
    "@react-three/postprocessing": "^2.6.2",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "moment": "^2.29.4",
    "nanoid": "^4.0.0",
    "nipplejs": "^0.9.1",
    "react": "^18.2.0",
    "react-animated-cursor": "^2.5.1",
    "react-dom": "^18.2.0",
    "react-favicon": "^1.0.1",
    "react-ga": "^3.3.1",
    "react-joyride": "^2.5.3",
    "react-scripts": "5.0.1",
    "simple-peer": "^9.11.1",
    "socket.io-client": "^4.5.2",
    "three": "^0.144.0",
    "use-sound": "^4.0.1",
    "web-vitals": "^2.1.4"

**Comment by CodyJasonBennett** [comment]
I published a workaround in [`v1.0.3`](https://github.com/pmndrs/its-fine/releases/tag/v1.0.3). Can you try another clean-install (remove lockfiles, `node_modules`)?

**Comment by abhi-dasgupta** [comment]
in my project its-fine is a sub-dependency of react-three-fiber, so I'll still get v1.0.2

**Comment by CodyJasonBennett** [comment]
Alright, I bumped its-fine in [`v8.8.5`](https://github.com/pmndrs/react-three-fiber/releases/tag/v8.8.5) of react-three-fiber if you could try now.

**Comment by abhi-dasgupta** [comment]
yes everything is working now. Thank you for looking into it

**Comment by CodyJasonBennett** [comment]
@hakancunier let me know if there are any withstanding issues on your end. This looks to be resolved between CRA and vanilla Webpack with the work around from #14.

**Comment by hakancunier** [comment]
Hello. I got it working by upgrading react-scripts ^5.0.1. Thank you again.
