### ISSUE TITLE
Multiple Contexts

### ISSUE THREAD

**Issue by dennemark** [pmndrs/its-fine#20]
Hi,
I tried to use its-fine together with tunnel-rats. Each tunnel having a different context provider.
However, its-fine spreads only one context provider to all tunnels, namely the last. The reason seems to be here:

https://github.com/pmndrs/its-fine/blob/3839c0a71927784a72d9dbd0a3a7749f45eff590/src/index.tsx#L187

If we move these two variables within the `useContextBridge`, the issue is resolved.

You can have a look into this codesandbox: https://codesandbox.io/s/compassionate-varahamihira-yxqqu7?file=/src/App.tsx
Check the console. `CompDOM` and `CompNIL` are the same except that NIL consumes context via its-fine. To try the correct version, just comment out `import ... 'its-fine'` and uncomment `import ... './itsFine'`
Check the video on how to do it.
It also shows where `contexts` and `variables` are placed within `useContextBridge`.

[useContextBridge.webm](https://user-images.githubusercontent.com/29654902/207303944-9a89829c-5eda-4b44-a347-8c9c3b1e99ff.webm)

**Comment by CodyJasonBennett** [comment]
Yeah, `contexts` and `values` would have to live within the hook to support this use case. If you want to create a PR with them in a lazy useState or useMemo I can publish a quick patch. Traversal in this area is pending optimization though, it's a hard problem.

**Comment by CodyJasonBennett** [comment]
Fix published in [v1.0.7](https://github.com/pmndrs/its-fine/releases/tag/v1.0.7).
