### ISSUE TITLE
Export 'useId' (imported as 'React') was not found in 'react'

### ISSUE THREAD

**Issue by Box777-k** [pmndrs/its-fine#25]
export 'useId' (imported as 'React') was not found in 'react'

when building app, webpack gives an error that there is no export useId in the module 'react'

here is bug in WebPack, from contributors material UI 
[in webpack issues 14814](https://github.com/webpack/webpack/issues/14814)

in [this](https://github.com/webpack/webpack/issues/14814#issuecomment-1013856049) comment trying gto fix them.

![image](https://user-images.githubusercontent.com/19405073/223637938-2a4ef6c3-4560-42e7-9918-5761aa8a2d98.png)

**Comment by CodyJasonBennett** [comment]
See #24, this library, and by extension `react-konva`, requires React 18 as a peer dependency.
