### ISSUE TITLE
Not working on React 19.0.0

### ISSUE THREAD

**Issue by veksa** [pmndrs/its-fine#38]
There is a crash on the 19.0.0 version of react (checked on 19.0.0-rc-3edc000d-20240926)

`TypeError: Cannot destructure property 'ReactCurrentOwner' of 'react__WEBPACK_IMPORTED_MODULE_0__.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED' as it is undefined.`

**Comment by CodyJasonBennett** [comment]
Your version of its-fine is very outdated. Are you using react-three-fiber? We have an alpha release under v9 which targets React 19.

**Comment by veksa** [comment]
i'm using react-konva, found related PR here: https://github.com/konvajs/react-konva/pull/802

thanks :)
